---
abstract: 'The Mason web framework'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::Class::Most: 0
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Poet
no_index:
  directory:
    - lib/Poet/t
    - lib/Poet/Test
    - lib/Poet/App.pm
    - lib/Poet/App
    - lib/Poet/Mason/Plugin.pm
    - lib/Poet/Mason/Plugin
    - lib/Poet/Types.pm
    - lib/Poet/Util.pm
recommends:
  Log::Any::Adapter::Log4perl: 0
  Log::Log4perl: 0
requires:
  CHI: 0.52
  Capture::Tiny: 0
  Data::Rmap: 0.6
  File::ShareDir: 0
  File::ShareDir::Install: 0
  File::Slurp: 0
  File::Spec::Functions: 0
  Guard: 0
  JSON::XS: 0
  Log::Any::Adapter: 0
  Mason: 2.19
  Mason::Plugin::Cache: 0
  Mason::Plugin::HTMLFilters: 0
  Mason::Plugin::RouterSimple: 0.05
  MasonX::ProcessDir: 0.02
  Method::Signatures::Simple: 1.02
  Moose: 1.15
  MooseX::App::Cmd: 0
  MooseX::HasDefaults::RO: 0
  MooseX::StrictConstructor: 0
  Plack: 0
  Plack::Middleware::Debug: 0
  Plack::Middleware::Session: 0
  Plack::Session::Store::Cache: 0
  Try::Tiny: 0
  URI: 0
  URI::Escape: 0
  YAML::XS: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Poet
  repository: git://github.com/jonswar/perl-poet.git
version: 0.11
